### ISSUE TITLE
Fail to build application by using docker-compose .

### ISSUE THREAD

**Issue by Joy-Zhang-0303** [openboxes/openboxes#1605]
Hello, openboxes team,

when I build the application by using docker-compose, I meet the belowing error. 
you can also confirm the situtation by the attached picture.
I need your help to solve this issue. I need to use Openboxes as soon as possiable.

Thanks.

> Unable to load specified config location classpath:openboxes-config.properties : class path resource [openboxes-config.properties] cannot be opened because it does not exist
> tomcat_1  | Unable to load specified config location classpath:openboxes-config.groovy : class path resource [openboxes-config.groovy] cannot be opened because it does not exist
> tomcat_1  | Unable to load specified config location file:/root/.grails/openboxes-config.groovy : /root/.grails/openboxes-config.groovy (No such file or directory)
![Screenshot from 2020-04-23 20-23-20](https://user-images.githubusercontent.com/48177679/80094259-eca94800-85a0-11ea-974c-611c24816d3d.png)

**Comment by jmiranda** [comment]
Thanks @Joy-Zhang-0303. Don't worry about the "Unable to load specified config location" errors. As you can see there are 4 config locations and only 3 "Unable to load" errors, which implies that it found one of the property files. The real issue is with the "Cannot invoke method with getAt()" error. This usually indicates that Java 8 is the culprit. I think it might be that the Tomcat 7 docker image was compiled with Java 8. I'll see if there's an image compiled with Java 7.

**Comment by Joy-Zhang-0303** [comment]
@jmiranda  

OK, Thanks for your information and quick reply .  
Looking forward to good news.

H.Z

**Comment by jmiranda** [comment]
@Joy-Zhang-0303 So I was able to reproduce the issue and find a quick fix. The long term solution will be for us to upgrade to Grails 3 (which we are in the process of doing) so that Java 8 is no longer a problem. 

In the short term, you can downgrade your Tomcat version to something like 7.0.90. 
```
  tomcat:
    image: tomcat:7.0.90
    ports:
      - "8072:8080"
    volumes:
      - ./openboxes.war:/usr/local/tomcat/webapps/openboxes.war
      - ./openboxes-config.properties:/root/.grails/openboxes-config.properties
    environment:
      CATALINA_OPTS: "$CATALINA_OPTS -server -Xms1024m -Xmx2024m -XX:MaxPermSize=256m -Djava.security.egd=file:/dev/./urandom"
```

NOTE: Please do not run this in production (or even as a public-facing test server) without addressing all security vulnerabilities identified between Tomcat 7.0.90-7.0.99 (especially CVE-2020-1938). I don't think we use AJP here, but the port might be open by default on older versions of Tomcat.
Here's a list of vulnerabilities that you should consider patching before making this publicly available.
https://tomcat.apache.org/security-7.html#Apache_Tomcat_7.x_vulnerabilities
