### ISSUE TITLE
ReCAPTCHA seems to be enabled by default

### ISSUE THREAD

**Issue by jmiranda** [openboxes/openboxes#3637]
https://discuss.openboxes.com/t/context-openboxes-startup-failed-due-to-previous-errors/680/5?u=jmiranda

**Comment by ewaterman** [comment]
I'm closing this out since we now have captcha disabled by default in our `application.yml` file:
```
openboxes:
    signup:
        recaptcha:
            enabled: false
```
